version: '3.9'
services:
  api:
    build:
       context: .
       dockerfile: Dockerfile
    restart: always
#    image: dossovmarlen/todolist:${IMAGE_TAG}
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
    ports:
      - '8000:8000'
    env_file:
      - ./.env
    volumes:
      - .:/app
    networks:
      - todolist_default


  migrations:
    build:
      context: .
      dockerfile: Dockerfile
#    image: dossovmarlen/todolist:${IMAGE_TAG}
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
    env_file:
      - ./.env
    volumes:
      - .:/app
    command: sh -c "python manage.py migrate"
    networks:
      - todolist_default

  postgres:
    image: postgres:12.4-alpine
    environment:
      POSTGRES_USER:  ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    ports:
      - "${DB_PORT:-5432}:5432"
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - todolist_default


volumes:
  pgdata:

networks:
  todolist_default:
    driver: bridge