# Generated by Django 4.2.4 on 2023-08-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="factory",
            name="debt_to_supplier",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Задолженность перед поставщиком",
            ),
        ),
        migrations.AddField(
            model_name="individualentrepreneur",
            name="debt_to_supplier",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Задолженность перед поставщиком",
            ),
        ),
        migrations.AddField(
            model_name="retailnetwork",
            name="debt_to_supplier",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Задолженность перед поставщиком",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="debt_to_supplier",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Задолженность перед поставщиком",
            ),
        ),
    ]
