# Generated by Django 4.2.4 on 2023-08-04 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0002_factory_debt_to_supplier_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="individualentrepreneur",
            old_name="house_number",
            new_name="number",
        ),
    ]
